CREATE SCHEMA IF NOT EXISTS DB_RESTAURANTES;
USE DB_RESTAURANTES;

/* RESTAURANTES */

CREATE TABLE DIRECCION_REST (
	COD_POST INT PRIMARY KEY AUTO_INCREMENT,
    PROVINCIA VARCHAR(25) NOT NULL,
    CANTON VARCHAR(25) NOT NULL,
    DISTRITO VARCHAR(25) NOT NULL,
    DIRECC_EXACTA VARCHAR(200) NOT NULL
);

CREATE TABLE RESTAURANTE (
	COD_REST INT PRIMARY KEY AUTO_INCREMENT,
    COD_POST INT NOT NULL,
    MENU_REST VARCHAR(200) NOT NULL,
    NOM_REST VARCHAR(100) NOT NULL,
    FOREIGN KEY (COD_POST) REFERENCES DIRECCION_REST(COD_POST)
);

/* RECETAS */

CREATE TABLE DIFICULTAD_RECETA(
	DIFICULTAD_RECETA INT PRIMARY KEY AUTO_INCREMENT,
    TIPO_DIFICULTAD VARCHAR(40) NOT NULL
);

CREATE TABLE TIPO_RECETA(
	COD_TIPO_RECETA INT PRIMARY KEY AUTO_INCREMENT,
    DIFICULTAD_RECETA INT NOT NULL,
    TIPO_RECETA VARCHAR(50) NOT NULL,
    DESCRIPCION_RECETA VARCHAR(200) NOT NULL,
    INGREDIENTES VARCHAR(100) NOT NULL,
    TIEMPO_PREP VARCHAR(50) NOT NULL,
    PROCEDIMIENTO VARCHAR(200) NOT NULL,
    FOREIGN KEY (DIFICULTAD_RECETA) REFERENCES DIFICULTAD_RECETA(DIFICULTAD_RECETA)
);

CREATE TABLE RECETAS (
	COD_RECETA INT PRIMARY KEY AUTO_INCREMENT,
    COD_TIPO_RECETA INT NOT NULL,
    NOM_RECETA VARCHAR(50) NOT NULL,
    FOREIGN KEY(COD_TIPO_RECETA) REFERENCES TIPO_RECETA(COD_TIPO_RECETA)
);

/* USUARIOS */

CREATE TABLE USUARIO (
	ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    COD_REST INT NOT NULL,
    COD_RECETA INT NOT NULL,
    NOM_USUARIO VARCHAR(25) NOT NULL,
    PASS_USUARIO VARCHAR(50) NOT NULL,
    FOREIGN KEY (COD_REST) REFERENCES RESTAURANTE(COD_REST),
    FOREIGN KEY (COD_RECETA) REFERENCES RECETAS(COD_RECETA)
);